FROM python:3.11.5
WORKDIR /app
COPY /ML_Training/flask_app/ /app
RUN pip install --no-cache-dir -r requirements.txt
ENV CUDA_VISIBLE_DEVICES=""
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app", "--workers", "1", "--timeout", "3000"]